name: Sync Docs to Plain on Mintlify Check Success

on:
  check_run:
    types: [completed]

jobs:
  sync:
    name: Sync Documents to Plain
    if: >
      github.event.check_run.name == 'Mintlify Deployment' &&
      github.event.check_run.conclusion == 'success' &&
      (github.event.check_run.app.slug == 'mintlify' || github.event.check_run.app.name == 'Mintlify')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install a stable version of sitemapper
        run: npm install -g sitemapper@^6.0.0

      - name: Install Plain CLI
        run: npm install -g @team-plain/cli@latest

      - name: Index Documents
        run: plain index-sitemap https://docs.meetjamie.ai/sitemap.xml
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY }} 