name: Sync Docs to Plain on Mintlify Check Success

on:
  check_run:
    types: [completed] # Only run when a check run is completed

jobs:
  sync:
    name: Sync Documents to Plain
    # Only run if the specific Mintlify check run was successful
    if: >
      github.event.check_run.name == 'Mintlify Deployment' &&
      github.event.check_run.conclusion == 'success' &&
      (github.event.check_run.app.slug == 'mintlify' || github.event.check_run.app.name == 'Mintlify') # Verify app slug or name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Plain CLI
        run: npm install -g @team-plain/cli@latest

      - name: Index Documents
        # Replace with your actual Mintlify sitemap URL
        run: plain index-sitemap https://docs.meetjamie.ai/
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY }} 